### ISSUE TITLE
Add more flexibility to read inputs

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/transit_model#737]
previously there was a method `gtfs::read_from_url` that was quite handy to read a gtfs from the network (and is used by https://github.com/etalab/transpo-rt/) but the dependency to `reqwest` was slowing down the compilation time of transit_model without being directly used by it.

It makes however the upgrade to the newest version of transit_model impossible for transpo-rt (because `FileHandler` and `gtfs::read` are not public).

I see several way to make this possible

## A: put back the reqwest dependency
:+1: easiest solution
:+1: can be used by kisio too
:-1: build time

## B: put back the reqwest dependency behind a feature
:+1: easy solution
:+1: can be used by kisio too
:-1: :-1: build time for ci (if ci is run for both feature, else :+1: )
:+1:  build time for other crates using transit_model without feature (like tartare-tools) 

## C: expose a way to do the `reqwest` call externally
I think we could expose a `gtfs::from_ziped_read` (not fan of the name if you have suggestion)
```rust
mod gtfs {

pub fn from_ziped_read<P: AsRef<Path>>(
    reader: R,
    source_name: &str,  // it's a bother but `source_name` is useful here to have nicer error msg
)-> Result<Model> 
where
    R: std::io::Seek + std::io::Read {
    let mut file_handle = read_utils::ZipHandler::new(reader, &source_name)?;
    read(&mut file_handle, config_path, prefix)
}
}
```
and in another crate (like [transpo-rt](https://github.com/etalab/transpo-rt/))
```rust
fn read_url(url: &str) -> Result<std::io::Cursor<Vec<u8>>> {
    let mut res = reqwest::get(url)?;
    let mut body = Vec::new();
    res.read_to_end(&mut body)?;
    Ok(std::io::Cursor::new(body))
}

pub fn main() -> Result<()> {
    let url = "http://pouet.zip";
    let r = read_url(&url)?;
    let model = gtfs::from_ziped_read(r, &url)?;
}
```
(it could be added to transit_model doc to make it easier)
:-1: more code but not too complex
:+1: can be used for other stuff (like a POC for WASM done by @datanel )
:+1: build time

what do you think about this? I'd personally vote for B + C :stuck_out_tongue_winking_eye:

**Comment by woshilapin** [comment]
I would say yes for option C, even if the `source_name` is pretty weird but that is mostly exposing a weirdness of `ZipHandler::new()` (but now, this weirdness will be publicly exposed :cry:).

Although, for sure we would need to find a better name for the function. At the very least, I would say `from_read()` would be enough (the fact that it is a ZIP can be documented if needed but sending a GTFS as one block should be understood as sending a ZIP (since it's the specification).

As for option A vs B, if we really want to go back to `reqwest`, I would go for B. But if we implement C, I would say that would considerably lower the need for such a feature. So I'm not saying no to B, but I'd like C to be implemented first, and see later if there is a serious need for B.
