### ISSUE TITLE
FR: prefixes dans les id

### ISSUE THREAD

**Issue by ue71603** [CanalTP/transit_model#764]
Pour l'utilisation au dehors de la France. Il devrait être possible t'assigner un prefix, qui on choisi.

example:
maintenant:  <Line id="FR:Line:47:" version="any">
exigé: <Line id="CH:1:887:Line:47:" version="any">

**Comment by pbougue** [comment]
Je n'ai pas compris le besoin, pouvez-vous préciser ?
----
I don't understand the need.
Maybe it is easier to express it in english :gb:?

**Comment by ue71603** [comment]
I see, the problem is that XML is removed, when saving.
We want to transform https://data.oebb.at/oebb?dataset=uddi:cd36722f-1b9a-11e8-8087-b71b4f81793a

All id have currently the following structure: FR:DayTypeAssignment:000000:
As this is data from Austria, we would like to have id that look like that   AT:oebb:DayTypeAssignment:000000: or something like that. So the question is: Could the prefix be defined in the command line (e.g. --prefix "AT:oebb" )

**Comment by woshilapin** [comment]
It would be possible to do that, but it's probably not desirable since `gtfs2netexfr` is supposed to produce French NeTEx, not Austrian NeTEx (and there might be differences). See my [other comments for more details](https://github.com/CanalTP/transit_model/issues/765#issuecomment-818658388). We could plan for the following options:
- create another binary `gtfs2netexau`
- rename `gtfs2netexfr` into `gtfs2netex` and add a new input option like `--profile fr` or `--profile au`

Even if these options are possibly good options, we don't really have the resources to do that at the moment. If you're willing to contribute, we can provide guidance and help to bootstrap the design and review the contributions.

**Comment by ue71603** [comment]
Thanks for the input and I see your point of view. We will discuss if we go in that direction. If we do, we would contact you again with a concrete pull request. So I think we close it here.
